### ISSUE TITLE
Recent change breaks builds in Go 1.14

### ISSUE THREAD

**Issue by alvarotuso** [silenceper/gowatch#35]
Even though `go.mod` specifies 1.14: https://github.com/silenceper/gowatch/blob/master/go.mod#L3

This breaks 1.14 builds: https://github.com/silenceper/gowatch/pull/34/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R98

The correct module for 1.14 is `ioutil`: https://pkg.go.dev/io/ioutil#WriteFile

The resulting error is:
```
# github.com/silenceper/gowatch
--
  | src/github.com/silenceper/gowatch/main.go:98:8: undefined: os.WriteFile
```

**Comment by silenceper** [comment]
yes, you are right. 
Thanks for your feedback.
